In [16]:
import pandas as pd
import numpy as np

In [17]:
data = pd.read_csv("./USA_Housing.csv")
data = data.drop("Address", axis=1)

In [18]:
X = data.drop("Price", axis=1).values
y = data["Price"].values

In [19]:
X[:5]

array([[7.95454586e+04, 5.68286132e+00, 7.00918814e+00, 4.09000000e+00,
        2.30868005e+04],
       [7.92486425e+04, 6.00289981e+00, 6.73082102e+00, 3.09000000e+00,
        4.01730722e+04],
       [6.12870672e+04, 5.86588984e+00, 8.51272743e+00, 5.13000000e+00,
        3.68821594e+04],
       [6.33452400e+04, 7.18823609e+00, 5.58672866e+00, 3.26000000e+00,
        3.43102428e+04],
       [5.99821972e+04, 5.04055452e+00, 7.83938779e+00, 4.23000000e+00,
        2.63541095e+04]])

In [20]:
y

array([1059033.55787012, 1505890.91484695, 1058987.98787608, ...,
       1030729.58315229, 1198656.87240769, 1298950.48026696],
      shape=(5000,))

In [21]:
train_size = int(0.7 * len(X))
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

In [22]:
X_train = np.hstack([np.ones((len(X_train), 1)), X_train])

In [23]:
# Tính toán các hệ số hồi quy bằng công thức:
# w = (X^T*X)^(-1)*X^T*y

In [24]:
XTX = np.dot(X_train.T, X_train)
XTX_inv = np.linalg.inv(XTX)
XTY = np.dot(X_train.T, y_train)
w = np.dot(XTX_inv, XTY)

In [25]:
w

array([-2.63619779e+06,  2.16785327e+01,  1.65557313e+05,  1.20430516e+05,
        1.06216590e+03,  1.51419972e+01])

In [26]:
var1 = 79248.642454
var2 = 6.002899
var3 = 6.73082
var4 = 3.09
var5 = 40173.07217

In [27]:
def predict_price(var1, var2, var3, var4, var5):
    input_vars = np.array([1, var1, var2, var3, var4, var5])
    return np.dot(input_vars, w)

In [28]:
pred = round(predict_price(var1, var2, var3, var4, var5))

In [29]:
print("Giá nhà dự đoán:", pred)

Giá nhà dự đoán: 1497799
